### PR TITLE
Detector details page wrappers fix

### LINKED ISSUE #384: [BUG] The detector details shouldn't have a wrapper around the whole page
**What is the bug?**
The detector details page has a wrapper around the whole page.

**How can one reproduce the bug?**
1. Go to detectors
2. Click on any detector to open the details page

**What is the expected behavior?**
The detector details page shouldn't have a wrapper around the whole page, title should not be within the wrapper, as it is not in other pages.

**Do you have any screenshots?**
This is how it should look like.
alert_page_without-frame

This is what it looks now.
detector-details-with-frame

### LINKED ISSUE #385: [BUG] The detector details shouldn't have a wrapper around the Active rules table
**What is the bug?**
The detector details have a wrapper around the Active rules table

**How can one reproduce the bug?**
1. Go to the detectors
2. Click on any detector to open the detectors page

**What is the expected behavior?**
The detector details shouldn't have a wrapper around the Active rules table

**Do you have any screenshots?**
This is how it should be.
active_rules_without_inner_wrapper

This is how it is now.
active_rules_inner_wrapper

### PR DESCRIPTION
**Pull request by jovancacvetkovic**
### Description
Resolves:
[BUG] The detector details shouldn't have a wrapper around the whole page
[BUG] The detector details shouldn't have a wrapper around the Active rules table

### Issues Resolved
Closes #384 
Closes #385 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by AWSHurneyt — APPROVED** [review]

File: public/pages/Rules/containers/Rules/Rules.tsx [hunk 1]
```diff
@@ -119,7 +119,9 @@ export const Rules: React.FC<RulesProps> = (props) => {
           <EuiSpacer size={'m'} />
         </EuiFlexItem>
         <EuiFlexItem>
-          <RulesTable loading={loading} ruleItems={ruleItems} showRuleDetails={setFlyoutData} />
+          <EuiPanel>
```
Comment (amsiglan) [inline public/pages/Rules/containers/Rules/Rules.tsx:122]: We don't need this panel. It will add an extra layer around the table as shown below:
image

Comment (jovancacvetkovic) [reply public/pages/Rules/containers/Rules/Rules.tsx:122]: It should not, I removed that panel from RulesTable.tsx, table should be a clean table, and add that wrapper where needed.

Comment (amsiglan) [reply public/pages/Rules/containers/Rules/Rules.tsx:122]: Got it

**Review by amsiglan — APPROVED** [review]

**Comment by amsiglan** [comment]
The test failure is in an unrelated part of the app, so it is safe to merge this change
