### PR TITLE
[BUG] Finding's fly-out has no correlations if open from alerts

### LINKED ISSUE #557: [BUG] Finding's fly-out has no correlations if open from alerts
**What is the bug?**
Finding's fly-out has no correlations if open from the alerts page.

**How can one reproduce the bug?**
1. Go to the alerts page
2. Open alert fly-out
3. Open findings fly-out
4. Switch to the findings tab
5. There are no correlations

Note: If one goes to the Findings page and then to the findings fly-out, there are correlations present.

**What is the expected behavior?**
Correlations should be present in the findings fly-out.

**Do you have any screenshots?**

### PR DESCRIPTION
**Pull request by jovancacvetkovic**
### Description
Fixing finding's fly-out has no correlations if open from the alerts page.

### Issues Resolved
Resolves #557 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/pages/Findings/components/FindingDetailsFlyout.tsx [hunk 1]
```diff
@@ -107,6 +107,16 @@ export default class FindingDetailsFlyout extends Component<
           this.setState({ correlatedFindings });
         }
       });
+  };
+
+  componentDidMount(): void {
+    this.getIndexPatternId().then((patternId) => {
```
Comment (AWSHurneyt) [inline public/pages/Findings/components/FindingDetailsFlyout.tsx:113]: Clarification question. Would the use of `.then()` here cause a slight delay when attempting to load the flyout? Would it be better to make use of a `loading` state to generate an "empty" flyout which then gets populated with data once the API call completes?

Comment (jovancacvetkovic) [reply public/pages/Findings/components/FindingDetailsFlyout.tsx:113]: Yeah, makes sense. I have created an issue as this is something that needs a bit more work https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/559

**Review by AWSHurneyt — APPROVED** [review]

File: public/pages/Findings/components/FindingDetailsFlyout.tsx [hunk 2]
```diff
@@ -83,16 +83,16 @@ export default class FindingDetailsFlyout extends Component<
...
-        this.setState({ indexPatternId: patternId });
-      }
-    });
-
+  getCorrelations = async () => {
     const { id, detector } = this.props.finding;
-    const allFindings = this.props.findings;
-    DataStore.correlationsStore
+    let allFindings = this.props.findings;
+    if (allFindings.length === 1 && allFindings[0].id === id) {
```
Comment (amsiglan) [inline public/pages/Findings/components/FindingDetailsFlyout.tsx:89]: We shouldn't take the count as the source of truth here since this can change anytime and also this will be true if there is only finding in the system.

Let's use a prop to check the source of the open action

Comment (jovancacvetkovic) [reply public/pages/Findings/components/FindingDetailsFlyout.tsx:89]: Gotcha, let me refactor this part.

Comment (jovancacvetkovic) [reply public/pages/Findings/components/FindingDetailsFlyout.tsx]: Done

**Review by amsiglan — APPROVED** [review]

**Comment by amsiglan** [comment]
Failing test is flaky and passed for windows runner
